### ISSUE TITLE
warning: unusable help text  found on pkg install

### ISSUE THREAD

**Issue by allthatsounds** [gnu-octave/pkg#1]
Hi, we are currently preparing a new release for the LTFAT package. 
Thereby, when testing our package, we got the following 2 warnings:

>>pkg install testdir

warning: doc_cache_create: unusable help text found in file 'playrec'
warning: called from
    doc_cache_create>handle_function at line 98 column 5
    doc_cache_create>create_cache at line 118 column 36
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 20
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

warning: doc_cache_create: unusable help text found in file 'polyboolmex'
warning: called from
    doc_cache_create>handle_function at line 98 column 5
    doc_cache_create>create_cache at line 118 column 36
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 20
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 619 column 9

The two concerning files are the only files we have that are built as mex-files, thus, I suppose it is not surprising that no usable help text has been found. For our .oct files, there is no such problem, and neither has there been one in the past. I figure that the problem arises in get_help_text() already, but since the warnings concern the install process, I thought, I'd flag it here first. Would it be possible to get this fixed? Or, alternatively, could you suggest a quick fix on our part to remove that warning?

Thanks, ats

**Comment by siko1056** [comment]
Hello @allthatsounds ,

The question is an upstream Octave issue, as `pkg` only uses Octave functions to extract help text.

A similar question was asked about classdef classes https://octave.discourse.group/t/fixing-unusable-help-text-found-in-warnings/1334/2

Do the mex file contain help text that can be displayed by Octave's help function?  If you only strive for Matlab compatibility, you have to safely ignore this warning.  I would not consider this a blocker for a package release.

**Comment by allthatsounds** [comment]
The release is out, this can be closed. Many thanks for your help!
